language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint codecov codeclimate-test-reporter dot'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt default'
  - 'codecov coverage/cobertura/cobertura-coverage.xml --token=691a6715-555f-490c-9808-85c3ea4e0430'
  - 'CODECLIMATE_REPO_TOKEN=898715e040e240acd84e0bb88a870c5f14015f467c6df413cfd50aebfe0e99a6 codeclimate-test-reporter < coverage/lcov/lcov.info'
